/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gomokugui;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author Wang
 */
public class MainFrame extends javax.swing.JFrame {
    private static MainFrame instance=null;
    private final JButton[][] board=new JButton[15][15];
    private Thread listenerThread;
    private PrintWriter outputWriter;
    private Process process;
    private boolean playerTurn;
    static ImageIcon EMPTY,BLACK,WHITE;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {  
        initComponents();
        init();
    }
    
    private void init(){
        ImageIcon rawIcon=new ImageIcon("image/empty.png");
        EMPTY=new ImageIcon(rawIcon.getImage().getScaledInstance(50,50,Image.SCALE_DEFAULT));
        rawIcon=new ImageIcon("image/black.png");
        BLACK=new ImageIcon(rawIcon.getImage().getScaledInstance(50,50,Image.SCALE_DEFAULT));
        rawIcon=new ImageIcon("image/white.png");
        WHITE=new ImageIcon(rawIcon.getImage().getScaledInstance(50,50,Image.SCALE_DEFAULT));       
        jLabel4.setVisible(false);
        jLabel3.setIcon(WHITE);
        jLabel2.setIcon(BLACK);
        playerTurn=false;
        final int size=50;
        for (int i=0;i<15;i++){
            for (int j=0;j<15;j++){
                JButton temp=new JButton();
                temp.setBounds(100+i*size, 100+j*size,size,size);
                temp.setVisible(true);
                temp.setIcon(EMPTY);
                temp.setBorder(null);
                temp.setEnabled(true);
                temp.addActionListener(new ButtonClickListener());
                this.add(temp);
                board[i][j]=temp;
            }
        }
    }
    
    private void turn(){
        playerTurn=!playerTurn;
        if (playerTurn){
            jLabel3.setForeground(Color.RED);
            jLabel2.setForeground(Color.BLACK);
        }
        else{
            jLabel2.setForeground(Color.RED);
            jLabel3.setForeground(Color.BLACK);
        }
    }
    
    private void clearBoard(){
        for (int i=0;i<15;i++){
            for (int j=0;j<15;j++){
                board[i][j].setIcon(EMPTY);
            }
        }
    }
    
    class ButtonClickListener implements ActionListener{
        final int size =50;
        @Override
        public void actionPerformed(ActionEvent ae) {
            JButton button=(JButton)ae.getSource();
            if (!button.getIcon().equals(EMPTY) || !playerTurn) return;
            button.setIcon(WHITE);
            int x=(button.getX()-100)/size;
            int y=(button.getY()-100)/size;
            System.out.println("Player: "+x+" "+y);
            turn();
            outputWriter.write(x+" "+y+"\r\n");
            outputWriter.flush();
        }
    }
    
    public void gameOver(boolean win){
        if (win){
            jLabel4.setText("你赢了");           
        }
        else{
            jLabel4.setText("你输了");
        }        
        jLabel4.setVisible(true);
        listenerThread.interrupt();      
    }
    
    /**
     * 黑棋在指定位置落子
     * @param x 落子位置的x坐标
     * @param y 落子位置的y坐标
     */
    public void putBlackChess(int x,int y){
        turn();
        board[x][y].setIcon(BLACK);             
    }

    
    public static MainFrame getInstance(){
        if (instance==null){
            instance=new MainFrame();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 153, 255));
        setPreferredSize(new java.awt.Dimension(1200, 1000));

        jLabel1.setFont(new java.awt.Font("楷体", 1, 48)); // NOI18N
        jLabel1.setText("AI五子棋");

        jLabel2.setFont(new java.awt.Font("楷体", 1, 36)); // NOI18N
        jLabel2.setText("AI");

        jLabel3.setBackground(new java.awt.Color(204, 255, 204));
        jLabel3.setFont(new java.awt.Font("楷体", 1, 36)); // NOI18N
        jLabel3.setText("Player");

        jButton1.setFont(new java.awt.Font("楷体", 1, 48)); // NOI18N
        jButton1.setText("开始游戏");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("楷体", 1, 48)); // NOI18N
        jButton2.setText("结束游戏");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("楷体", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("你赢了！");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(642, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)))
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 60, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(31, 31, 31)
                .addComponent(jButton2)
                .addGap(56, 56, 56)
                .addComponent(jLabel4)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * 开始游戏按钮的点击事件
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if (!jButton1.getText().equals("开始游戏")){
                clearBoard();             
                listenerThread.interrupt();      
                outputWriter.write("exit\r\n");
                outputWriter.flush();
                process.destroy();
            }            
            playerTurn=false;
            jButton1.setText("重新开始");
            jLabel4.setVisible(false);
            process=Runtime.getRuntime().exec("cmd.exe /c AI");    
            OutputStream pOutputStream = process.getOutputStream();
            outputWriter = new PrintWriter(pOutputStream, true);   
            listenerThread=new ProcessListener(process);
            listenerThread.start();
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        listenerThread.interrupt();
        outputWriter.write("exit\r\n");
        outputWriter.flush();
        process.destroy();
        this.setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
